# Generated by Django 6.0.5 on 2026-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comparativaVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=40)),
                ('dataPrece', models.CharField(max_length=40)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('importoPrece', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diferenza', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='prodotiOra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('orario', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unita', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vendutoOra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('fasciaOraria', models.CharField(max_length=50)),
                ('incassi', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('nomeProdutto', models.CharField(max_length=50)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unita', models.FloatField()),
                ('totPer', models.CharField(max_length=10)),
            ],
        ),
    ]
